# Generated by Django 4.0.4 on 2022-05-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ingredients',
            new_name='components',
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post_g', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='posts.post')),
            ],
        ),
    ]
