version: '3.7'

services:
  foodbook:
    build: ./
    container_name: foodbook
    command: bash entrypoint.sh
    volumes:
      - .:/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0
    container_name: foodbook_db
    volumes:
      - foodbook_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: foodbook_nginx
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - foodbook

volumes:
  foodbook_postgres_data: